-- MySQL 8.0.16+; fails safely if this project database already exists.
CREATE DATABASE hr_attrition_portfolio CHARACTER SET utf8mb4;
USE hr_attrition_portfolio;
CREATE TABLE employee_snapshot (
  `Age` INT UNSIGNED NOT NULL,
  `Attrition` VARCHAR(64) NOT NULL,
  `BusinessTravel` VARCHAR(64) NOT NULL,
  `DailyRate` INT UNSIGNED NOT NULL,
  `Department` VARCHAR(64) NOT NULL,
  `DistanceFromHome` INT UNSIGNED NOT NULL,
  `Education` INT UNSIGNED NOT NULL,
  `EducationField` VARCHAR(64) NOT NULL,
  `EmployeeCount` INT UNSIGNED NOT NULL,
  `EmployeeNumber` INT UNSIGNED NOT NULL,
  `EnvironmentSatisfaction` INT UNSIGNED NOT NULL,
  `Gender` VARCHAR(64) NOT NULL,
  `HourlyRate` INT UNSIGNED NOT NULL,
  `JobInvolvement` INT UNSIGNED NOT NULL,
  `JobLevel` INT UNSIGNED NOT NULL,
  `JobRole` VARCHAR(64) NOT NULL,
  `JobSatisfaction` INT UNSIGNED NOT NULL,
  `MaritalStatus` VARCHAR(64) NOT NULL,
  `MonthlyIncome` INT UNSIGNED NOT NULL,
  `MonthlyRate` INT UNSIGNED NOT NULL,
  `NumCompaniesWorked` INT UNSIGNED NOT NULL,
  `Over18` VARCHAR(64) NOT NULL,
  `OverTime` VARCHAR(64) NOT NULL,
  `PercentSalaryHike` INT UNSIGNED NOT NULL,
  `PerformanceRating` INT UNSIGNED NOT NULL,
  `RelationshipSatisfaction` INT UNSIGNED NOT NULL,
  `StandardHours` INT UNSIGNED NOT NULL,
  `StockOptionLevel` INT UNSIGNED NOT NULL,
  `TotalWorkingYears` INT UNSIGNED NOT NULL,
  `TrainingTimesLastYear` INT UNSIGNED NOT NULL,
  `WorkLifeBalance` INT UNSIGNED NOT NULL,
  `YearsAtCompany` INT UNSIGNED NOT NULL,
  `YearsInCurrentRole` INT UNSIGNED NOT NULL,
  `YearsSinceLastPromotion` INT UNSIGNED NOT NULL,
  `YearsWithCurrManager` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`EmployeeNumber`),
  CHECK (`Attrition` IN ('Yes','No')),
  CHECK (`OverTime` IN ('Yes','No')),
  CHECK (`JobSatisfaction` BETWEEN 1 AND 4),
  CHECK (`Age` >= 18)
) ENGINE=InnoDB;
